sudo: required
services:
  - docker

before_install:
  - docker build -t kengonline/bookstore-web-docker -f Dockerfile.dev .

script:
  - docker run kengonline/bookstore-web-docker npm test -- --coverage