sudo: required
services:
  - docker

before_install:
  - docker build -t kengonline/bookstore-web-docker -f Dockerfile.dev .

script:
  - docker run kengonline/bookstore-web-docker npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: docker-app
  env: "DockerApp-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-179397784370"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"